<fieldset>
    <legend class="screen-reader-text"><?php _e('Additional robots.txt rules','xml-sitemap-feed'); ?></legend>
	<label>
        <?php printf(__('Rules that will be appended to the %s generated by WordPress:','xml-sitemap-feed'),'<a href="'.trailingslashit(get_bloginfo('url')).'robots.txt" target="_blank">robots.txt</a>'); ?>
        <br>
        <textarea name="<?php echo $this->prefix; ?>robots" id="xmlsf_robots" class="large-text" cols="50" rows="6"><?php echo esc_attr( trim(parent::get_robots()) ); ?></textarea>
    </label>
	<p class="description">
        <?php _e('These rules will not have effect when you are using a static robots.txt file.','xml-sitemap-feed'); ?>
        <br>
        <span style="color: red" class="warning">
            <?php _e('Only add rules here when you know what you are doing, otherwise you might break search engine access to your site.','xml-sitemap-feed'); ?>
        </span>
    </p>
</fieldset>